name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install cross compiler
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build for Windows
        run: |
          export GOOS=windows
          export GOARCH=amd64
          export CGO_ENABLED=1
          export CC=x86_64-w64-mingw32-gcc
          go build -ldflags "-s -w -H=windowsgui" -o bin/Video_Downloader.exe main.go

      - name: Create Release File
        run: |
          cp config.yaml bin/config.yaml
          tar -cvf Video_Downloader.tar.gz bin/config.yaml bin/Video_Downloader.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Video_Downloader.tar.gz
            bin/Video_Downloader.exe
            bin/config.yaml
          token: ${{ secrets.TOKEN }}